config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :posts

  devise_for :users

  root 'home#index'

  get '/users/sign_out' => 'device/sessions#destroy'

  resources :todos

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #
  # DEACTIVATED FOR THE SAKE OF THE DEMO
  # protect_from_forgery with: :exception
  # after_filter :manage_headers

  def after_sign_in_path_for(resource)
    todos_url
  end

  def manage_headers
    response.headers = response.headers.except("X-Frame-Options")
    puts response.headers
  end
end

app/controllers/csrf_controller.rb
class CsrfController < ApplicationController
  def index
    # TODO: gbataille - get cookies to display
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create
    todo = Todo.new(todo_params)
    if todo.save
      flash[:notice] = todo_params.to_s
      redirect_to todos_url, creation_params: todo_params
    else
      redirect_to new_todos_url
    end
  end

  def index
    @todos = Todo.all
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :detail, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csrf_helper.rb
module CsrfHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.haml
%h1 Home#index
=link_to 'CSRF Tuto', todos_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecuTuto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%# TODO: gbataille - remove those links%>
    <span>
      <%=link_to "Todos", todos_url %> | 
    </span>
    <span>
      <%=link_to "New Todo", new_todo_url %>
      </span>
  </div>
  <div class="session">
    <%if (current_user) %>
      Logged in as <%=current_user.email %>, with cookie <%=cookies[:_CSRFTuto_session]%>
      <%=button_to "Sign out", destroy_user_session_url, method: :delete %>
    <%else %>
        Not logged in
    <% end -%>
  </div>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

<%= yield %>

</body>
</html>

app/views/todos/index.html.haml
%h1 Todos
- for todo in @todos
  %p
    %h5=todo.title
    =todo.quantity
    x
    =todo.detail

%p
  =link_to "Add item", new_todo_url

app/views/todos/new.html.haml
%h1 New Todo Item
=form_for :todo, url: todos_url do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :detail
    =f.text_field :detail
  %p
    =f.label :quantity
    =f.text_field :quantity
  %p
    =f.submit "Add"